name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/production-docker-stack:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/production-docker-stack:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: 'arn:aws:iam::492184390594:role/production-docker-github-actions'
          aws-region: 'eu-central-1'

      - name: Deploy to EC2
        run: |
          COMPOSE_B64=$(base64 -w 0 docker-compose.yml)
          NGINX_B64=$(base64 -w 0 nginx/nginx.conf)
          PROMETHEUS_B64=$(base64 -w 0 monitoring/prometheus.yml)

          COMMAND_ID=$(aws ssm send-command \
            --instance-ids i-0367155e15770d3e4 \
            --document-name AWS-RunShellScript \
            --parameters "commands=[
              \"mkdir -p /opt/production-docker-stack/nginx\",
              \"mkdir -p /opt/production-docker-stack/monitoring\",
              \"echo $COMPOSE_B64 | base64 -d > /opt/production-docker-stack/docker-compose.yml\",
              \"echo $NGINX_B64 | base64 -d > /opt/production-docker-stack/nginx/nginx.conf\",
              \"echo $PROMETHEUS_B64 | base64 -d > /opt/production-docker-stack/monitoring/prometheus.yml\",
              \"cd /opt/production-docker-stack\",
              \"docker compose config\",
              \"docker compose pull\",
              \"docker compose up -d\",
              \"docker image prune -f\",
              \"docker compose ps\"
            ]" \
            --region eu-central-1 \
            --query 'Command.CommandId' \
            --output text)

          echo "SSM Command ID: $COMMAND_ID"

          aws ssm wait command-executed \
            --command-id "$COMMAND_ID" \
            --instance-id i-0367155e15770d3e4 \
            --region eu-central-1

          aws ssm get-command-invocation \
            --command-id "$COMMAND_ID" \
            --instance-id i-0367155e15770d3e4 \
            --region eu-central-1
